### PR TITLE
FEATURE: TS Rewrite

### LINKED ISSUE #6: Allow setting string values via the preset color selector to choose theme colors
This would allow setting css classes but using the colors for the selection.

### LINKED ISSUE #53: Option to reset presetColors
If i only have 5 "Preset Colors" for example i didn't found a way to disable all the others in the presetColors Array.

### LINKED ISSUE #65: Hide alpha value in hex mode
If the mode is set to `hex`, the alpha values should be hidden, or (even better) the alpha value should be deactivatable

CleanShot 2022-10-17 at 12 12 16@2x

### PR DESCRIPTION
**Pull request by Sebobo**
- [x] Convert code to TypeScript
- [x] Replace ReactCSS with CSS modules
- [x] Use functional components
- [x] Resolve #65 
- [x] Resolve #53 
- [x] Resolve #6 
- [x] Reduce bundle size (currently 123KB -> 112KB)

### CODE REVIEW

**Comment by Sebobo** [comment]
@jonnitto would love to have you as reviewer of this PR 🙂

**Comment by jonnitto** [comment]
The `preset` mode doesn't seem to work correctly:

```yaml
presethex:
      type: string
      ui:
        label: 'Preset mode with hex values'
        inspector:
          editor: 'Shel.Neos.ColorPicker/ColorPickerEditor'
          editorOptions:
            mode: preset
            presetColors:
              - '#ff0000'
              - '#00ff00'
            allowEmpty: true
```


https://user-images.githubusercontent.com/4510166/198326341-18067019-2673-4658-a0e9-c98c6841003d.mp4

**Comment by jonnitto** [comment]
Also, the preset mode with non-hex values doesn't work correctly:

```yaml
preset:
      type: string
      ui:
        label: 'Preset mode with objects'
        inspector:
          editor: 'Shel.Neos.ColorPicker/ColorPickerEditor'
          editorOptions:
            mode: preset
            presetColors:
              - color: rgb(var(--color-main-theme))
                label: 'Main'
                value: 'main'
              - color: green
                label: 'Grün'
                value: 'minor'
              - color: '#ff0000'
                label: 'Rot'
                value: red
            allowEmpty: true
```

**Comment by jonnitto** [comment]
The `hsla` field show the fields with `rgba` values, but in this mode, I would expect the `hsla` values
CleanShot 2022-10-27 at 17 05 39@2x

**Comment by jonnitto** [comment]
With alpha hidden, you could make the height of the color bar higher:

CleanShot 2022-10-27 at 17 06 59@2x

**Comment by Sebobo** [comment]
Thx for testing everything !!!

> The `preset` mode doesn't seem to work correctly:

- [x] Fixed (only affected string only presets)

> Also, the preset mode with non-hex values doesn't work correctly:

⚠️ This is currently not supported. I adjusted the readme to show this limitation

> With alpha hidden, you could make the height of the color bar higher:

- [x] Adjusted the styles

> The color bar is missing the drag handle:

- [x] Fixed

> The hsla field show the fields with rgba values, but in this mode, I would expect the hsla values

- [ ] The fields component needs to be adapted for that

**Review by jonnitto — APPROVED** [review]

**Review by jonnitto — APPROVED** [review]

**Pull request merged**
